config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { registrations: 'users/registrations' }
  root to: 'pages#home'

  resources :products, only: [:index, :show, :create, :destroy] do

    resources :reviews, only: :create

    resources :wishlist_products, only: [:show, :create]

  end

  resource :account, only: [:show, :edit, :update] do
    resources :wishlists,         only: [:index, :edit, :update, :destroy]
    resources :wishlist_products, only: [:destroy]
  end

  namespace :merchant do
    resources :products
  end

  namespace :profile do

    resource :user, only: [:show, :update]
  end

end

app/views/shared/_catbar.html.erb
<div class="col-xs-12 no-gutter">

  <!-- categories bar -->
  <div class="hidden-xs hidden-sm col-md-12 categories-white-wrapper">
    <div class="hidden-xs hidden-sm col-md-10 col-md-offset-1 col-lg-6 col-lg-offset-3 text-center no-gutter">
      <div class="categories-bar">
        <div class="container">
          <div class="row">

            <ul>
              <div class="dropdown">
                <li class="<%= category_filter_css_class("women") %>" class="dropbtn"><%= link_to "WOMEN", products_path(category: "women") %></li>
                <div class="dropdown-content">
                <li class="<%= category_filter_css_class("dresses") %>"><%= link_to "Dresses", products_path(category: "dresses") %></li>
                <li class="<%= category_filter_css_class("jackets & coats") %>"><%= link_to "Jackets & Coats", products_path(category: "jackets & coats") %></li>
                <li class="<%= category_filter_css_class("knitwear") %>"><%= link_to "Knitwear", products_path(category: "knitwear") %></li>
                <li class="<%= category_filter_css_class("jeans & denim") %>"><%= link_to "Jeans & Denim", products_path(category: "jeans & denim") %></li>
                <li class="<%= category_filter_css_class("jumpsuits & playsuits") %>"><%= link_to "Jumpsuits & Playsuits", products_path(category: "jumpsuits & playsuits") %></li>
                <li class="<%= category_filter_css_class("tops") %>"><%= link_to "Tops", products_path(category: "tops") %></li>
                <li class="<%= category_filter_css_class("skirts") %>"><%= link_to "Skirts", products_path(category: "skirts") %></li>
                <li class="<%= category_filter_css_class("trousers") %>"><%= link_to "Trousers", products_path(category: "trousers") %></li>
                <li class="<%= category_filter_css_class("Nightwear & Lingerie") %>"><%= link_to "Nightwear & Lingerie", products_path(category: "nightwear & lingerie") %></li>
                <li class="<%= category_filter_css_class("bags") %>"><%= link_to "Bags", products_path(category: "bags") %></li>
                <li class="<%= category_filter_css_class("shoes") %>"><%= link_to "Shoes", products_path(category: "shoes") %></li>
                <li class="<%= category_filter_css_class("accessories") %>"><%= link_to "Accessories", products_path(category: "accessories") %></li>

                </div>
              </div>


              <div class="dropdown">
                <li class="<%= category_filter_css_class("men") %>" class="dropbtn"><%= link_to "MEN", products_path(category: "men") %></li>
                <div class="dropdown-content">
                <li class="<%= category_filter_css_class("tops & t-shirts") %>"><%= link_to "Tops & T-shirts", products_path(category: "tops & t-shirts") %></li>
                <li class="<%= category_filter_css_class("coats & jackets") %>"><%= link_to "Coats & Jackets", products_path(category: "coats & jackets") %></li>
                <li class="<%= category_filter_css_class("knitwear") %>"><%= link_to "Knitwear", products_path(category: "knitwear") %></li>
                <li class="<%= category_filter_css_class("jeans & denim") %>"><%= link_to "Jeans & Denim", products_path(category: "jeans & denim") %></li>
                <li class="<%= category_filter_css_class("shirts") %>"><%= link_to "Shirts", products_path(category: "shirts") %></li>
                <li class="<%= category_filter_css_class("trousers & shorts") %>"><%= link_to "Trousers & Shorts", products_path(category: "trousers & shorts") %></li>
                <li class="<%= category_filter_css_class("suits & tailoring") %>"><%= link_to "Suits & Tailoring", products_path(category: "suits & tailoring") %></li>
                <li class="<%= category_filter_css_class("underwear & nightwear") %>"><%= link_to "Underwear & Nightwear", products_path(category: "underwear & nightwear") %></li>
                <li class="<%= category_filter_css_class("sportswear") %>"><%= link_to "Sportswear", products_path(category: "sportswear") %></li>
                <li class="<%= category_filter_css_class("bags") %>"><%= link_to "Bags", products_path(category: "bags") %></li>
                 <li class="<%= category_filter_css_class("shoes") %>"><%= link_to "Shoes", products_path(category: "shoes") %></li>
                 <li class="<%= category_filter_css_class("accessories") %>"><%= link_to "Accessories", products_path(category: "accessories") %></li>
               </div>
             </div>

             <div class="dropdown">
               <li class="<%= category_filter_css_class("kids") %>" class="dropbtn"><%= link_to "KIDS", products_path(category: "kids") %></li>
               <div class="dropdown-content">
               <li class="<%= category_filter_css_class("baby gifts") %>"><%= link_to "Baby Gifts", products_path(category: "girls clothes") %></li>
               <li class="<%= category_filter_css_class("girls clothes") %>"><%= link_to "Girls Clothes", products_path(category: "girls clothes") %></li>
               <li class="<%= category_filter_css_class("boys clothes") %>"><%= link_to "Boys Clothes", products_path(category: "boys clothes") %></li>
               <li class="<%= category_filter_css_class("accessories") %>"><%= link_to "Accessories", products_path(category: "accessories") %></li>
               </div>
             </div>

             <li class="<%= category_filter_css_class("shops") %>"><%= link_to "SHOPS", products_path(category: "shops") %></li>

             <li class="<%= category_filter_css_class("bags") %>"><%= link_to "BRANDS", products_path(category: "bags") %></li>

             <li class="<%= category_filter_css_class("coats") %>"><%= link_to "TOP SALES", products_path(category: "coats") %></li>
           </div>
         </div>
       </div>
     </div>
   </div>
 </ul>
 <!-- end categories bar -->

</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div id="flash" class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div id="flash" class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="col-xs-12 no-gutter">

  <div id="footer">
    <div class="container">
      <div class="row">

        <div class="col-xs-12 text-center footer-icons">
          <ul class="list-inline">
            <li class="font-icons-bold">Follow us on &nbsp; </li>
            <li><a href=""><i class="fa fa-youtube"></i></a></li>
            <li><a href="https://www.instagram.com/salesquare/" target="_blank"><i class="fa fa-instagram"></i></a></li>
            <li><a href=""><i class="fa fa-facebook"></i></a></li>
            <li><a href="https://twitter.com/shopsalesquare" target="_blank"><i class="fa fa-twitter"></i></a></li>
          </ul>
        </div>

        <div class="col-xs-12 text-center footer-pages">
          <ul class="list-inline">
            <li><a href=""><p>About</p></a></li>
            <li><a href=""><p>FAQ</p></a></li>
            <li><a href=""><p>Care</p></a></li>
            <li><a href=""><p>Merchants</p></a></li>
            <li><a href=""><p>Contact</p></a></li>
          </ul>
        </div>

        <div class="col-xs-12 text-center footer-terms">
          <ul class="list-inline">
            <li><a href=""><p>©2016 Salesquare</p></a></li>
            <li><p>|</p></a></li>
            <li><a href=""><p>Terms</p></a></li>
            <li><p>|</p></a></li>
            <li><a href=""><p>Privacy Policy</p></a></li>
          </ul>
        </div>

      </div>
    </div>
  </div>

</div>

app/views/shared/_navbar.html.erb
<div class="col-xs-12 no-gutter navbar-white-wrapper">

  <!-- Logo -->
  <div class="col-xs-6 col-sm-6 col-md-3 no-gutter">
    <div class="col-xs-12 col-sm-12 col-lg-offset-4 col-lg-8 no-gutter">
      <div class="navbar-left-logo">

        <%= link_to root_path, class: "logoo" do %>
        <%= image_tag "logo.svg" %>
        <% end %>

      </div>
    </div>
  </div>
  <!-- End Logo -->

  <!-- Searchbar -->
  <div class="hidden-xs hidden-sm col-md-6 no-gutter">
    <div class="navbar-center-search">

      <form action="/products" method="get" class="navbar-center-search-form">
        <%= hidden_field_tag :category, @category %>
        <span class="fa fa-search"></span>
        <input type="text" name="search_term" class="navbar-center-search-bar" placeholder="Search..." value="<%= @search_term %>">
      </form>

    </div>
  </div>
  <!-- End Searchbar

  <!-- Right Navigation -->
  <div class="hidden-xs hidden-sm col-md-3 no-gutter">
    <div class="col-xs-12 col-sm-12 col-lg-8 no-gutter">
      <div class="navbar-right-links">

        <% if user_signed_in? %>

        <!-- Different navigation for logged in / not logged in -->

        <!-- Profile picture and Dropdown -->
        <div class="navbar-wagon-item">
          <div class="dropdown">

            <% if current_user.photo.present? %>
            <%= image_tag current_user.photo.url, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>

            <% else %>
            <%= image_tag "noavatar.png", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
            <% end %>

            <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
              <li>
                <%= link_to profile_user_path do %>
                <i class="fa fa-user"></i> profile
                <% end %>
              </li>
              <li>
                <%= link_to account_wishlists_path do %>
                <i class="fa fa-star"></i> wishlist
                <% end %>
              </li>
              <li>
                <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t ".sign_out", default: "Log out" %>
                <% end %>
              </li>
            </ul>
          </div>
        </div>
        <!-- End Profile picture and Dropdown -->
        <!-- End Different navigation for logged in / not logged in -->

        <% else %>

        <!-- Sign up and Log in links -->
        <%= link_to t(".sign_in", default: "Sign up"), new_user_registration_path, class: "reg-color-black" %>

        <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "reg-color-black" %>
        <!-- End Sign up and Log in links -->

        <% end %>

      </div>
    </div>
  </div>
  <!-- End Right Navigation -->

  <!-- Dropdown list (mobile) -->
  <div class="col-xs-6 col-sm-6 hidden-md hidden-lg no-gutter">
    <div class="navbar-right-mobile">

      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">

        <% if user_signed_in?  %>
        <li><%= link_to "profile", profile_user_path %></li>
        <% else %>
        <li> <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "reg-color-black" %> </li>
        <% end %>

        <li><%= link_to "shop", products_path %></li>
      </ul>

    </div>
  </div>
  <!-- End Dropdown list (mobile) -->

</div>