config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { registrations: 'users/registrations' }
  root to: 'pages#home'

  resources :products, only: [:index, :show, :create, :destroy] do

    resources :reviews, only: :create

    resources :wishlist_products, only: [:show, :create]

  end

  resource :account, only: [:show, :edit, :update] do
    resources :wishlists,         only: [:index, :edit, :update, :destroy]
    resources :wishlist_products, only: [:destroy]
  end

  namespace :merchant do
    resources :products
  end

  namespace :profile do

    resource :user, only: [:show, :update]
  end

end

app/models/wishlist.rb
class Wishlist < ActiveRecord::Base
  belongs_to :user
  has_many :wishlist_products, dependent: :destroy
  has_many :products, through: :wishlist_products
end

app/controllers/wishlists_controller.rb
class WishlistsController < ApplicationController

  def index
    @wishlists = current_user.wishlists
  end

  def edit
    @wishlist = current_user.wishlists.find(params[:id])
  end

  def update
    @wishlist = current_user.wishlists.find(params[:id])

    if @wishlist.update(account_wishlist_params)
      redirect_to account_wishlists_path
      flash[:notice] = "it worked"
    else
      redirect_to root_path
      flash[:warning] = "it didn't work"
    end
  end

  def destroy
    @wishlist = current_user.wishlists.find(params[:id])
    @wishlist.destroy
    redirect_to account_wishlists_path
  end

  private

  def account_wishlist_params
    params.require(:wishlist).permit(:name)
  end

end

app/helpers/wishlists_helper.rb
module WishlistsHelper
end

app/views/wishlists/_changeWishlistName.html.erb
<div class="modal fade" id="<%= wishlist.id %>modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">
          <span aria-hidden="true">&times;</span>
          <span class="sr-only">Close</span>
        </button>
        <h4 class="modal-title" id="myModalLabel">
          Change the name of your Wishlist
        </h4>
      </div>
      <div class="modal-body">
        <% if user_signed_in? %>
        <div>
          <%= simple_form_for [current_user, wishlist], url: account_wishlist_path(wishlist) do |f| %>
          <%= f.input :name, label: wishlist.name %>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default"
        data-dismiss="modal">
        Close
      </button>
          <%= f.submit "change name of wishlist", class: "btn btn-primary" %>
        <% end %>
          <% end %>
    </div>
  </div>
  </div>
</div>

app/views/wishlists/index.html.erb
<div class="text-center"><h1>Your Wishlists</h1>
  <p>Go to a product and click 'add to wishlist'</p>
</div>

<div class="container">
  <div class="row">

    <% @wishlists.each do |wishlist| %>
    <div class="col-xs-12 col-md-4">
      <div class="wishlist-wrapper">

        <!-- wishlist options -->
        <h3><%= wishlist.name %></h3>
        <%= link_to "##{wishlist.id}modal", "data-toggle" => "modal" do %>
        <i class="fa fa-pencil"></i>
        <% end %>
        <%= render partial: "changeWishlistName", locals: { wishlist: wishlist } %>

        <%= link_to account_wishlist_path(wishlist), method: :delete, data: { confirm: 'You are about to delete the wishlist, are you sure?'} do %>
        <i class="fa fa-times-circle"></i>
        <% end %>
        <!-- wishlist options end -->

        <!-- wishlist items -->
        <% wishlist.wishlist_products.each do |wishlist_product| %>
        <%= link_to product_path(wishlist_product.product) do %>

        <!-- content -->
        <div class="wishlist-content">

          <%= cl_image_tag wishlist_product.product.photo.url(:wishlist), class: "pic-size" %>

          <div class="wishlist-content-info">

          <p><%= truncate(wishlist_product.product.name.strip, length: 17) %></p>
            <p><%= humanized_money_with_symbol(wishlist_product.product.price) %></p>

          </div>
          <!-- content end -->

          <!-- wishlist item options -->
          <%= link_to account_wishlist_product_path(wishlist_product), method: :delete, data: { confirm: 'You are about to delete the product from your wishlist, are you sure?'} do%>
          <i class="fa fa-times-circle"></i>
          <% end %>
          <!-- wishlist item options end -->

        </div>
        <% end %>
        <% end %>
        <!-- wishlist items end-->

      </div>
    </div>
    <% end %>
  </div>
</div>