config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { registrations: 'users/registrations' }
  root to: 'pages#home'

  resources :products, only: [:index, :show, :create, :destroy] do

    resources :reviews, only: :create

    resources :wishlist_products, only: [:show, :create]

  end

  resource :account, only: [:show, :edit, :update] do
    resources :wishlists,         only: [:index, :edit, :update, :destroy]
    resources :wishlist_products, only: [:destroy]
  end

  namespace :merchant do
    resources :products
  end

  namespace :profile do

    resource :user, only: [:show, :update]
  end

end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :user
  has_many :reviews, dependent: :destroy
  has_many :wishlist_products, dependent: :destroy

  validates :name, :category, :price, :url, :photo, :description, presence: {message: "Field is required"}
  mount_uploader :photo, PhotoUploader

  monetize :price_cents
  # monetize :optional_price_cents, :allow_nil => true

  include PgSearch
  pg_search_scope :search, against: [ :name, :description, :category ]
end

app/controllers/merchant/products_controller.rb
class Merchant::ProductsController < ApplicationController
  include DeviseCreateUsers::MerchantsHelper
  before_action :check_merchant, only:[ :new, :create, :edit, :update, :destroy ]

  def index
    @products = current_user.products
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    @product.user = current_user
    if @product.save
      redirect_to product_path(@product)
    else
      render 'new'
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    @product.update(product_params)
    redirect_to product_path(@product)
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to merchant_products_path
  end

  private

  def product_params
    params.require(:product).permit(
      :name,
      :description,
      :photo,
      :photo_cache,
      :price,
      :url,
      :category
      )
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  skip_before_action :authenticate_user!, only:[ :index, :show ]

  add_breadcrumb "home", :root_path


  def index
    @category = params[:category]
    @search_term = params[:search_term]

    if @search_term
      @products = search_results
    else
      @products = Product.all
    end

    if @category == "men"
      @products = @products.where(category: "men")
    elsif @category == "women"
      @products = @products.where(category: "women")
    elsif @category == "kids"
      @products = @products.where(category: "kids")
    elsif @category == "bags"
      @products = @products.where(category: "bags")
    elsif @category == "shoes"
      @products = @products.where(category: "shoes")
    elsif @category == "dresses"
      @products = @products.where(category: "dresses")
    elsif @category == "coats"
      @products = @products.where(category: "coats")
    elsif @category == "blazers"
      @products = @products.where(category: "blazers")
    elsif @category == "jackets"
      @products = @products.where(category: "jackets")
    elsif @category == "jeans"
      @products = @products.where(category: "jeans")
    elsif @category == "lingerie"
      @products = @products.where(category: "lingerie")
    elsif @category == "shirts & blouses"
      @products = @products.where(category: "shirts & blouses")
    elsif @category == "skirts"
      @products = @products.where(category: "skirts")
    elsif @category == "socks & tights"
      @products = @products.where(category: "socks & tights")
    elsif @category == "baby gifts"
      @products = @products.where(category: "baby gifts")
    elsif @category == "accesories"
      @products = @products.where(category: "accesories")
    elsif @category == "jackets & coats"
      @products = @products.where(category: "coats")
    elsif @category == "hoodies & sweatshirts"
      @products = @products.where(category: "hoodies & sweatshirts")
    elsif @category == "shirts"
      @products = @products.where(category: "shirts")
    elsif @category == "cardigans & jumpsuits"
      @products = @products.where(category: "cardigans & jumpsuits")
    elsif @category == "trousers"
      @products = @products.where(category: "trousers")
    elsif @category == "shorts"
      @products = @products.where(category: "shorts")
    elsif @category == "t-shirts & vests"
      @products = @products.where(category: "t-shirts & vests")
    elsif @category == "socks"
      @products = @products.where(category: "socks")
    end

    add_breadcrumb "products", products_path
  end

  def search_results
    Product.search(@search_term)
  end

  def show
    @product = Product.find(params[:id])
    @review = Review.new
    @wishlist_product = WishlistProduct.new
    if user_signed_in?
      @wishlists = current_user.wishlists
    end
    add_breadcrumb "#{@product.category}", products_path(category: @product.category)
    add_breadcrumb "#{@product.name}", product_path
  end
end

app/helpers/devise_create_users/merchants_helper.rb
module DeviseCreateUsers::MerchantsHelper
  def check_merchant
    if !current_user.merchant
      flash[:error] = "Don't be stupid haha"
      redirect_to root_path
    end
  end
end

app/helpers/products_helper.rb
module ProductsHelper
  def category_filter_css_class(filter)
    return "active" if filter == @category
  end
end

app/views/merchant/products/edit.html.erb
<br>
<div class="login-wrapper text-center">
 <img src="http://unsplash.it/1002/250')" alt="">
 <div class="form-inputs salelogin"><h1>Edit Product</h1>

  <%= simple_form_for [:merchant, @product] do |f| %>
  <div class="form-group">
    <%= f.text_field :name,  autofocus: true,
    class: "finput",
      placeholder: "Title" %>
    </div>
    <div class="form-group">
      <%= f.text_field :price, class: "finput", placeholder: "Price (€)" %>
    </div>
    <div class="form-group">
      <%= f.text_field :description, class: "finput", placeholder: "Description" %>
    </div>
    <div class="form-group">
      <%= f.file_field :photo, class: "finput", placeholder: "Update photo" %>
      <%= f.hidden_field :photo_cache %>
    </div>
    <div class="form-group">
      <%= f.text_field :category, class: "finput", placeholder: "Category (men, women, etc..)" %>
    </div>
    <div class="form-group">
    <%= f.text_field :url, class: "finput", placeholder: "URL" %>
    </div>
    <div class="f-actions">
      <div class="form-actions">
        <%= f.submit class:"loginn" %>
      </div>
      <% end %>
    </div>
  </div>
</div>
<br>

app/views/merchant/products/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="hidden-sm col-md-2">
    </div>
    <div class="col-xs-12 col-md-8">
      <br>
      <div class="stripetrough text-center">
        <h2><span>All your posted products</span></h2>
        <p> Here you can edit and delete</p>
      </div>

      <div class="container-fluid text-center ">
        <div class="row">
          <div class="products">
            <% @products.each do |p| %>
            <div class="col-xs-12 col-md-3 paddingfix">
              <div class="products-wrapper">
                <div class="pimage">
                 <%= cl_image_tag p.photo.url(:bright_face) %>
               </div>
               <div class="pname">
                <h3><%= p.name %></h3>
              </div>


              <div class="pcategory">
                € <%= p.price %>
              </div>
              <hr/>
              <%= link_to product_path(p), class: "showproduct" do %>

              <div class="pcatlink">

          <%= link_to "show product", product_path(p), class: "showproduct" %> |
          <%= link_to "Delete", ([:merchant,p]), method: :delete, class: "deleteproduct" %> |
          <%= link_to "Edit", edit_merchant_product_path(p), class: "editproduct" %>

              </div>
              <% end %>

            </div>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="hidden-sm col-md-2">
  </div>
</div>
</div>

app/views/merchant/products/new.html.erb
<div class="form-wrapper">
<div class="registration-banner"></div>


 <div class="form-inputs salelogin">
      <div class="form-group">

  <%= simple_form_for [:merchant, @product] do |f| %>

  <%= f.input :name, label: false, placeholder: "Title", input_html: {class: "finput"} %>

  <%= f.input :price, label: false, placeholder: "Price (€)", input_html: {class: "finput"} %>

  <%= f.input :description, label: false, placeholder: "Description", input_html: {class: "finput"} %>

  <div class="photo-upload">

    <div class="photo-label">Upload a photo</div>
    <%= f.input :photo, input_html: {class: "finput"}, label: false %>
    <%= f.input :photo_cache, as: :hidden %>
  </div>

  <%= f.input :category, label: false, placeholder: "Category (men, women, etc..)", input_html: {class: "finput"} %>

  <%= f.input :url, label: false, placeholder: "URL", input_html: {class: "finput"} %>

  <div class="submit-button text-center">
  <%= f.button :submit %>
  </div>
</div>
</div>
<% end %>
</div>

app/views/merchant/products/show.html.erb
<h1> products detail</h1>

<%= image_tag @product.photo.url(:bright_face) %>
<h2><%= @product.name %></h2>
<p><%= @product.description %></p>
<p><%= @product.price %></p>
<p><%= @product.url %></p>